export interface FormData {
    id: number;
    readyPosition: string;
    pathImg: string;
    steps: string[];
    paro: string;
  }
  
  export const formsData: FormData[] = [
    {
      id: 12,
      readyPosition: "Parallel stance (naranhi sŏgi) at A facing D.",
      pathImg: "/paths/kibon.svg",
      steps: [
        "Begin by turning 90° toward B, forming a left-foot-forward front stance (oenbal apsŏgi) while executing a left high section forearm block (sangdan p'almok makki). Kihap.",
        "Step forward with right foot toward B, forming a right-foot-forward front stance (orŭnbal apsŏgi) while executing a right high section front punch (sangdan ap jumŏk jirŭgi).",
        "Turn right 180° toward C, forming a right-foot-forward front stance (orŭnbal apsŏgi) while executing a right high section forearm block (sangdan p'almok makki).",
        "Step forward with left foot toward C, forming a left-foot-forward front stance (oenbal apsŏgi) while executing a left high section front punch (sangdan ap jumŏk jirŭgi).",
        "Turn left 90° toward D, forming a left-foot-forward front stance (oenbal apsŏgi) while executing a left high section forearm block (sangdan p'almok makki).",
        "Step forward with your right foot toward D, forming a right-foot-forward front stance (orŭnbal apsŏgi) while executing a right high section front punch (sangdan ap jumŏk jirŭgi).",
        "Turn right 180° toward E, forming a right-foot-forward front stance (orŭnbal apsŏgi) while executing a right high section forearm block (sangdan p'almok makki).",
        "Step forward with left foot toward E, forming a left-foot-forward front stance (oenbal apsŏgi) while executing a left high section front punch (sangdan ap jumŏk jirŭgi).",
        "Turn right 180° toward D, forming a right-foot-forward front stance (orŭnbal apsŏgi) while executing a right high section forearm block (sangdan p'almok makki).",
        "Move forward toward D by executing a left leg front snap kick (ap ch'agi) and landing in a left-foot-forward front stance (oenbal apsŏgi). Maintain hand positions during kick.",
        "Without stepping forward, execute a left high section front punch (sangdan ap jumŏk jirŭgi) toward D.",
        "Without stepping forward, execute a right reverse high section front punch (sangdan bandae ap jumŏk jirŭgi). Kihap."
      ],
      paro: "Return left leg to ready position."
    },
    {
      id: 11,
      readyPosition: "Parallel stance (naranhi sŏgi) at A facing D.",
      pathImg: "/paths/kicho.svg",
      steps: [
        "Begin by stepping toward B, forming a left-foot-forward front stance (oenbal apsŏgi) while executing a left low section forearm block (hadan p'almok makki). Kihap.",
        "Maintain stance. Execute a left middle section forearm block (jungdan p'almok makki).",
        "Move forward toward B by executing a right leg front snap kick (ap ch'agi) and landing in a right-foot-forward front stance (orŭnbal apsŏgi).",
        "Without stepping forward, execute a right middle section front punch (jungdan ap jumŏk jirŭgi) toward B.",
        "Move forward toward B by executing a left leg front snap kick (ap ch'agi) and landing in a left-foot-forward front stance (oenbal apsŏgi).",
        "Without stepping forward, execute a left middle section front punch (jungdan ap jumŏk jirŭgi) toward B.",
        "Step forward with right foot toward B, forming a right-foot-forward front stance (orŭnbal apsŏgi) while executing a right middle section front punch (jungdan ap jumŏk jirŭgi).",
        "Without stepping forward, execute a left reverse middle section front punch (jungdan bandae ap jumŏk jirŭgi) toward B. Kihap.",
        "Moving your left foot, turn 270° counter-clockwise (left) toward C. Step into a left-foot-forward back stance (oenbal dwissŏgi) while executing a left middle section inside forearm block (jungdan an p'almok makki).",
        "Shift left leg into a left-foot-forward front stance (oenbal apsŏgi) while executing a left low section forearm block (hadan p'almok makki).",
        "Maintain stance while executing a left middle section forearm block (jungdan p'almok makki).",
        "Move forward toward C by executing a right leg front snap kick (ap ch'agi) and landing in a right-foot-forward front stance (orŭnbal apsŏgi).",
        "Without stepping forward, execute a right middle section front punch (jungdan ap jumŏk jirŭgi) toward C.",
        "Moving your right foot, turn 180° clockwise (right) toward D. Step into a right-foot-forward back stance (orŭnbal dwissŏgi) while executing a right middle section inside forearm block (jungdan an p'almok makki).",
        "Shift right leg into a right-foot-forward front stance (orŭnbal apsŏgi) while executing a right low section forearm block (hadan p'almok makki).",
        "Maintain stance while executing a right middle section forearm block (jungdan p'almok makki).",
        "Move forward toward D by executing a left leg front snap kick (ap ch'agi) and landing in a left-foot-forward front stance (oenbal apsŏgi).",
        "Without stepping forward, execute a left middle section front punch (jungdan ap jumŏk jirŭgi) toward D.",
        "Moving your left foot, turn 90° counter-clockwise (left) toward A. Step into a left-foot-forward front stance (oenbal apsŏgi), executing a left low section forearm block (hadan p'almok makki).",
        "Shift your right foot to your left foot, forming a transitional closed stance (moasŏgi). Step out with your left foot toward A, landing in a left-foot-forward front stance (oenbal apsŏgi), executing a left middle section forearm block (jungdan p'almok makki).",
        "Step forward toward A into a right-foot-forward front stance (orŭnbal apsŏgi), executing a right middle section front punch (jungdan ap jumŏk jirŭgi).",
        "Step forward toward A into a left-foot-forward front stance (oenbal apsŏgi), executing a left middle section front punch (jungdan ap jumŏk jirŭgi).",
        "Step forward toward A into a right-foot-forward front stance (orŭnbal apsŏgi), executing a right middle section front punch (jungdan ap jumŏk jirŭgi).",
        "Maintain stance and execute a left reverse middle section front punch (jungdan bandae ap jumŏk jirŭgi). Kihap."
      ],
      paro: "Return turning left leg counter-clockwise to ready position."
    },
    {
      id: 10,
      readyPosition: "Closed stance (moasŏgi) AKF hand position, at A facing D.",
      pathImg: "/paths/kyuki-il.svg",
      steps: [
        "Begin by stepping toward B, forming a left-foot-forward back stance (oenbal dwissŏgi) while executing a left middle section double knifehand block (jungdan dul sonk'al makki). Kihap.",
        "Shift left foot toward B, forming a left-foot-forward front stance (oenbal apsŏgi) while executing a right reverse middle section knifehand block (jungdan bandae sonk'al makki).",
        "Hook right hand and step with left foot onto line AB into a horse stance (gima sŏgi). Execute a left outside forearm strike (bakkat p'almok ddaerigi) to the elbow.",
        "Shift left foot to right into a transitional closed stance (moasŏgi). Step out with right foot into a right-foot-forward back stance (orŭnbal dwissŏgi) facing C while executing a right middle section double knifehand block (jungdan dul sonk'al makki).",
        "Shift right foot toward C, forming a right-foot-forward front stance (orŭnbal apsŏgi) while executing a left reverse middle section knifehand block (jungdan bandae sonk'al makki).",
        "Hook left hand and step with right foot onto line AC into a horse stance (gima sŏgi). Execute a right outside forearm strike (bakkat p'almok ddaerigi) to the elbow.",
        "Shift right foot to left foot into a transitional closed stance (moasŏgi). Step out with left foot toward D, forming a left-foot-forward back stance (oenbal dwissŏgi) while executing a left middle section double knifehand block (jungdan dul sonk'al makki).",
        "Shift left foot toward D, forming a left-foot-forward front stance (oenbal apsŏgi). Reach out with left hand and grab opponent's head. Execute a right reverse high section front elbow strike (sangdan bandae ap p'alkkumch'i jirŭgi) with your right elbow coming to meet your left hand.",
        "Step forward with your right foot into a right-foot-forward back stance (orŭnbal dwissŏgi) while executing a right middle section double knifehand block (jungdan dul sonk'al makki).",
        "Shift right foot toward D, forming a right-foot-forward front stance (orŭnbal apsŏgi). Reach out with right hand and grab opponent's head. Execute a left reverse high section front elbow strike (sangdan bandae ap p'alkkumch'i jirŭgi) with your left elbow coming to meet your right hand.",
        "Step forward toward D, forming a left-foot-forward front stance (oenbal apsŏgi). Execute a left middle section front punch (jungdan ap jumŏk jirŭgi).",
        "Maintain stance. Execute a right reverse middle section front punch (jungdan bandae ap jumŏk jirŭgi). Kihap.",
        "Look to your left at a 45° angle toward E, and bring your hands up to a guarding block (daebi makki). Execute a roundhouse kick (dollyŏ ch'agi) with your right leg. Land in a right-foot-forward front stance (orŭnbal apsŏgi) facing E. Immediately execute number 14.",
        "Maintain stance and execute a right middle section knifehand block (jungdan sonk'al makki).",
        "Maintain stance and execute a left reverse high section palm-heel strike (sangdan bandae sonbadak jirŭgi).",
        "Maintain stance and execute a right high section palm-heel strike (sangdan sonbadak jirŭgi). Kihap.",
        "Stepping backwards toward A, bring right foot to left forming a transitional closed stance (moasŏgi). Step back with left foot into a right-foot-forward back stance (orŭnbal dwissŏgi) executing a right low section double knifehand block (hadan dul sonk'al makki).",
        "Shift out with the right foot into a right-foot-forward front stance (orŭnbal apsŏgi) and execute a left reverse middle section front punch (jungdan bandae ap jumŏk jirŭgi).",
        "Maintain stance. Execute a right middle section front punch (jungdan ap jumŏk jirŭgi).",
        "Step backwards toward A into a left-foot-forward back stance (oenbal dwissŏgi) executing a left low section double knifehand block (hadan dul sonk'al makki).",
        "Shift out with the left foot into a left-foot-forward front stance (oenbal apsŏgi) and execute a right reverse middle section front punch (jungdan bandae ap jumŏk jirŭgi).",
        "Maintain stance. Execute a left middle section front punch (jungdan ap jumŏk jirŭgi).",
        "Step backward toward A forming a right-foot-forward back stance (orŭnbal dwissŏgi). Execute a right low section forearm block (hadan p'almok makki).",
        "Step backward toward A forming a left-foot-forward back stance (oenbal dwissŏgi). Execute a left low section forearm block (hadan p'almok makki).",
        "Step toward B with left foot forming a horse stance (gima sŏgi) and guarding to the left with a guarding block (daebi makki).",
        "Move toward B with a left step-behind side thrust kick (baldwiro olmkyŏ yŏp ch'agi). Land in a horse stance (gima sŏgi) and immediately execute number 27.",
        "Maintain stance. Execute a high section outward knifehand strike (sangdan bakkŭro sonk'al ddaerigi) with the left hand.",
        "Look over your right shoulder toward C. Bring left foot to right in a transitional closed stance (moasŏgi). Step out toward C with right foot into a horse stance (gima sŏgi) while executing a guarding block (daebi makki) toward C.",
        "Move toward C with a right step-behind side thrust kick (baldwiro olmkyŏ yŏp ch'agi). Land in a horse stance (gima sŏgi) and immediately execute number 30.",
        "Maintain stance. Execute a high section outward knifehand strike (sangdan bakkŭro sonk'al ddaerigi) with the right hand. Kihap."
      ],
      paro: "Return right leg to ready position."
    },
    {
      id: 9,
      readyPosition: "(moasŏgi) AKF hand position, at A facing forward.",
      pathImg: "/paths/kyuki-yee.svg",
      steps: [
        "Step left foot back toward B to form a right-foot-forward back stance (orŭnbal dwissŏgi). Execute a right middle section inside forearm block (jungdan an p'almok makki). Kihap.",
        "Maintain stance and execute a right hand low section palm-heel block (hadan sonbadak makki).",
        "Maintain stance and execute a left reverse middle section turning punch (jungdan bandae dollyŏ ap jumŏk jirŭgi).",
        "Step right leg back toward B to form a left-foot-forward back stance (oenbal dwissŏgi). Execute a left middle section inside forearm block (jungdan an p'almok makki).",
        "Maintain stance and execute a left hand low section palm-heel block (hadan sonbadak makki).",
        "Maintain stance and execute a right reverse middle section turning punch (jungdan bandae dollyŏ ap jumŏk jirŭgi).",
        "Step counter-clockwise 180° with the left foot, forming a horse stance (gima sŏgi) along line AB. Execute a middle section twin inside forearm block (jungdan ssang an p'almok makki).",
        "Step counter-clockwise with the left foot 180° toward A, forming a horse stance (gima sŏgi) along line AB. Execute a right high section backfist strike (sangdan dŭngjumŏk jirŭgi) while simultaneously executing a left low section forearm block (hadan p'almok makki).",
        "Move right leg counter-clockwise 180° toward A, forming a right-foot-forward fixed stance (orŭnbal gojŏng sŏgi). Execute a right middle section side punch (jungdan yŏp jumŏk jirŭgi). Kihap.",
        "Step counter-clockwise with left foot toward C, landing in a left-foot-forward back stance (oenbal dwissŏgi) facing C. Execute a left middle section inside forearm block (jungdan an p'almok makki).",
        "Maintain stance and execute a left hand low section palm-heel block (hadan sonbadak makki).",
        "Maintain stance and execute a right reverse middle section turning punch (jungdan bandae dollyŏ ap jumŏk jirŭgi).",
        "Step right leg forward toward C to form a right-foot-forward back stance (orŭnbal dwissŏgi). Execute a right middle section inside forearm block (jungdan an p'almok makki).",
        "Maintain stance and execute a right hand low section palm-heel block (hadan sonbadak makki).",
        "Maintain stance and execute a left reverse middle section turning punch (jungdan bandae dollyŏ ap jumŏk jirŭgi).",
        "Step clockwise 180° with the left foot, forming a horse stance (gima sŏgi) along line AC. Execute a middle section twin inside forearm block (jungdan ssang an p'almok makki).",
        "Step clockwise with the left foot 180° toward A, forming a horse stance (gima sŏgi) along line AC. Execute a right high section backfist strike (sangdan dŭngjumŏk jirŭgi) while simultaneously executing a left low section forearm block (hadan p'almok makki).",
        "Step right foot forward toward A to form a right-foot-forward back stance (orŭnbal dwissŏgi). Stack and execute a twin forearm box block (ssang son p'almok makki).",
        "Maintain stance and execute a left reverse middle section uppercut strike (jungdan bandae dwijibŏ jirŭgi), bringing your right fist to your left shoulder.",
        "Step left foot forward toward D to form a left-foot-forward back stance (oenbal dwissŏgi). Stack and execute a twin forearm box block (ssang son p'almok makki).",
        "Maintain stance and execute a right reverse middle section uppercut strike (jungdan bandae dwijibŏ jirŭgi), bringing your left fist to your right shoulder.",
        "Step forward into a right-foot-forward front stance (orŭnbal apsŏgi) executing an augmented block (gŏdŭrŏ makki) to the right.",
        "Maintain stance. Execute a left reverse low section forearm block (hadan bandae p'almok makki).",
        "Retract right arm, raise right foot slightly, land in same stance and execute a right high section front punch (sangdan ap jumŏk jirŭgi).",
        "Step forward into a left-foot-forward front stance (oenbal apsŏgi) executing an augmented block (gŏdŭrŏ makki) to the left.",
        "Maintain stance. Execute a right reverse low section forearm block (hadan bandae p'almok makki).",
        "Retract left arm, raise left foot slightly, land in same stance and execute a left high section front punch (sangdan ap jumŏk jirŭgi).",
        "Step left foot over to the right and pivot on left foot 180° toward A, forming a right-foot-forward front stance (orŭnbal apsŏgi) facing A. Execute a wedging knifehand block (haech'yŏ sonk'al makki).",
        "Step forward with left foot into a left-foot-forward front stance (oenbal apsŏgi), executing a right reverse high section upward elbow strike (sangdan bandae wi p'alkkumch'i ddaerigi) with the right elbow.",
        "Step onto line DC with right foot, forming a horse stance (gima sŏgi) facing front. Execute a middle section twin rear elbow strike (jungdan ssang dwi p'alkkumch'i ddaerigi).",
        "Maintain stance and execute a high section twin punch (sangdan ssang ap jumŏk jirŭgi) with the fists at a 45° angle. Kihap."
      ],
      paro: "Return right leg to ready position."
    },
    {
      id: 8,
      readyPosition: "Closed stance (moasŏgi) AKF hand position, at A facing B.",
      pathImg: "/paths/kyuki-sam.svg",
      steps: [
        "Right foot steps back toward C forming a left-foot-forward front stance (oenbal apsŏgi). Execute a left middle section forearm block (jungdan p'almok makki). Kihap.",
        "Step back with left foot forming a right-foot-forward front stance (orŭnbal apsŏgi). Execute a right high section palm-heel strike (sangdan sonbadak jirŭgi).",
        "Move forward executing a left inside-to-outside crescent kick (ap yŏk dollyŏ ch'agi). Continue immediately to movement 4.",
        "Execute a right leg roundhouse kick (dollyŏ ch'agi). Continue immediately to movement 5.",
        "Turn 180° backward toward B, executing a left leg spinning side thrust kick (dwidollyŏ yŏp ch'agi). Land in a left-foot-forward fixed stance (oenbal gojŏng sŏgi) and immediately execute movement number 6.",
        "Maintain stance and execute a left high section outward knifehand strike (sangdan bakkŭro sonk'al ddaerigi).",
        "Shift into a left kneeling front stance (murŭp kkulhŏ sŏgi) facing B (right knee should be on the ground). Execute a combination left high section knifehand block (sangdan sonk'al makki) and right reverse uppercut strike (bandae dwijibŏ ddaerigi). Kihap.",
        "Move left hand around opponent's head and execute a right reverse high section front elbow strike (sangdan bandae ap p'alkkumch'i jirŭgi) to the head. Bring the right elbow to the left hand; the right hand should end up over the left shoulder.",
        "Reach up, grab opponent's head and pull downward, throwing opponent to the right at a 45° angle.",
        "While holding opponent down, turn 180° to the right, shifting your weight from the right knee to the left knee. While still kneeling, execute a low section kneeling spin side thrust kick (hadan murŭp kkulhŏ dwidollyŏ yŏp ch'agi) with the right leg. You should be kneeling facing C while performing this kick.",
        "Push yourself up backwards, forming a left-foot-forward back stance (oenbal dwissŏgi), executing a middle section twin palm-heel pushing block (jungdan ssang sonbadak mirŏ makki).",
        "Step forward toward A into a right-foot-forward front stance (orŭnbal apsŏgi) and execute a low section X-forearm block (hadan gyoch'a p'almok makki).",
        "Step forward toward A into a left-foot-forward front stance (oenbal apsŏgi) and execute a high section X-forearm block (sangdan gyoch'a p'almok makki).",
        "Step back with left foot into a right-foot-forward front stance (orŭnbal apsŏgi) and execute a right middle section forearm block (jungdan p'almok makki).",
        "Step back again into a left-foot-forward front stance (oenbal apsŏgi) and execute a left high section palm-heel strike (sangdan sonbadak jirŭgi).",
        "Move forward executing a right inside-to-outside crescent kick (ap yŏk dollyŏ ch'agi). Continue immediately to movement 17.",
        "Execute a left leg roundhouse kick (dollyŏ ch'agi). Continue immediately to movement 18.",
        "Turn 180° backward toward C, executing a right leg spinning side thrust kick (dwidollyŏ yŏp ch'agi). Land in a right-foot-forward fixed stance (orŭnbal gojŏng sŏgi) and immediately execute movement number 19.",
        "Maintain stance and execute a right high section outward knifehand strike (sangdan bakkŭro sonk'al ddaerigi).",
        "Shift into a right kneeling front stance (murŭp kkulhŏ sŏgi) facing B. Execute a combination right high section knifehand block (sangdan sonk'al makki) and left reverse uppercut strike (bandae dwijibŏ ddaerigi). Kihap.",
        "Move right hand around opponent's head and execute a left reverse high section front elbow strike (sangdan bandae ap p'alkkumch'i jirŭgi) to the head. Bring the left elbow to the right hand; the left hand should end up over the right shoulder.",
        "Reach up, grab opponent's head and pull downward, throwing opponent to the left at a 45° angle.",
        "While holding opponent down, turn 180 degrees to the left, shifting your weight from the left knee to the right knee. While still kneeling, execute a low section kneeling spin side thrust kick (hadan murŭp kkulhŏ dwidollyŏ yŏp ch'agi) with the left leg. You should be kneeling facing B while performing this kick.",
        "Push yourself up backwards, forming a right-foot-forward back stance (orŭnbal dwissŏgi), executing a middle section twin palm-heel pushing block (jungdan ssang sonbadak mirŏ makki).",
        "Step forward toward A into a left-foot-forward front stance (oenbal apsŏgi) and execute a low section X-forearm block (hadan gyoch'a p'almok makki).",
        "Step forward toward A into a right-foot-forward front stance (orŭnbal apsŏgi) and execute a high section X-forearm block (sangdan gyoch'a p'almok makki).",
        "Execute a left leg low section twisting kick (hadan bit'ŭllyŏ ch'agi).",
        "Set the kicking leg down into a left-foot-forward front stance (oenbal apsŏgi) and execute a left high section front punch (sangdan ap jumŏk jirŭgi).",
        "Maintain stance and execute a reverse middle section front punch (jungdan bandae ap jumŏk jirŭgi). Kihap."],
      paro: "Return left leg to ready position."
    },
    {
      id: 7,
      readyPosition: "Parallel stance (naranhi sŏgi) with double arc hand pressing earth, at A facing E.",
      pathImg: "/paths/geunbon.svg",
      steps: [
        "Step back with right leg toward B and form a left-foot-forward front stance (oenbal apsŏgi). Execute a left low section forearm block (hadan p'almok makki)/right reverse middle section inside forearm block (jungdan bandae an p'almok makki). Kihap.",
        "Step back with left leg into a right-foot-forward front stance (orŭnbal apsŏgi). Execute a right low section forearm block (hadan p'almok makki)/left reverse middle section inside forearm block (jungdan bandae an p'almok makki).",
        "Step forward with left leg into a left-foot-forward back stance (oenbal dwissŏgi) and execute a left low section Kyuki-Do block (hadan gyŏkkido makki).",
        "Shift right foot to left foot into a transitional closed stance (moasŏgi). Step out with left foot toward C forming a left-foot-forward back stance (oenbal dwissŏgi). Stack and execute a modified box block (byŏn'gyŏng ssang son p'almok makki).",
        "Maintain stance and execute a right reverse high section inward knifehand strike (sangdan bandae anŭro sonk'al ddaerigi) to the neck. Bring your left fist to your right shoulder.",
        "Maintain stance and execute a left middle section side punch (jungdan yŏp jumŏk jirŭgi).",
        "Step forward toward C to form a right-foot-forward front stance (orŭnbal apsŏgi) and execute a right middle section front punch (jungdan ap jumŏk jirŭgi).",
        "Turn clockwise 180° degrees toward D and form a right-foot-forward back stance (orŭnbal dwissŏgi). Stack and execute a modified box block (byŏn'gyŏng ssang son p'almok makki).",
        "Maintain stance and execute a left reverse high section inward knifehand strike (sangdan bandae anŭro sonk'al ddaerigi) to the neck. Bring your right fist to your right shoulder.",
        "Maintain stance and execute a right middle section side punch (jungdan yŏp jumŏk jirŭgi).",
        "Step forward toward D to form a left-foot-forward front stance (oenbal apsŏgi) and execute a left middle section front punch (jungdan ap jumŏk jirŭgi).",
        "Turn left 90° degrees toward E and form a left-foot-forward back stance (oenbal dwissŏgi). Execute a middle section double knifehand block (jungdan dul sonk'al makki).",
        "Step forward toward E with a right leg front snap kick (ap ch'agi). Land in a transitional stance and immediately execute movement 14.",
        "Move forward toward E with a left leg roundhouse kick (dollyŏ ch'agi). Land in a transitional stance and immediately execute movement 15.",
        "Move forward toward E with a left leg step-behind side thrust kick (baldwiro olmkyŏ yŏp ch'agi) and land in a left-foot-forward front stance (oenbal apsŏgi). Immediately execute movement 16.",
        "Maintain stance and execute a right reverse high section downward hammerfist strike (sangdan bandae naeryŏ mejumŏk ddaerigi). Kihap.",
        "Step backward with left foot forming a right-foot-forward front stance (orŭnbal apsŏgi) and execute right middle section knifehand block (jungdan sonk'al makki).",
        "Execute right lead leg front snap kick (ap ch'agi) and step backward into a left-foot-forward front stance (oenbal apsŏgi).",
        "Maintain stance and execute a left middle section knifehand block (jungdan sonk'al makki).",
        "Execute a left lead leg front snap kick (ap ch'agi), step backward and pivot on right foot counter-clockwise onto line AE.",
        "Land in a horse stance (gima sŏgi) and execute a middle section double knifehand block (jungdan dul sonk'al makki) toward A.",
        "Execute a step-behind side thrust kick (baldwiro olmkyŏ yŏp ch'agi) toward A. Land at A and bring right leg to left leg in a transitional closed stance (moasŏgi).",
        "Step out with right foot 45° toward F, forming a right-foot-forward front stance (orŭnbal apsŏgi). Execute a wedging knifehand block (haech'yŏ sonk'al makki).",
        "Grab right hand with left hand and execute a left middle section knee strike (jungdan murŭp jirŭgi).",
        "Step left foot backward toward A, landing in a horse stance (gima sŏgi) along line AF. Execute a right downward elbow strike (naeryŏ p'alkkumch'i ddaerigi) with your palm facing your body. Kihap.",
        "Look 45° toward G. Shift right foot to left foot forming a transitional closed stance (moasŏgi). Step out with left foot 45° toward G, forming a left-foot-forward front stance (oenbal apsŏgi). Execute a wedging knifehand block (haech'yŏ sonk'al makki).",
        "Grab left hand with right hand and execute a right middle section knee strike (jungdan murŭp jirŭgi).",
        "Step right foot back toward A, landing in a horse stance (gima sŏgi) along line AF. Execute a left downward elbow strike (naeryŏ p'alkkumch'i ddaerigi) with your palm facing your body. Kihap."
      ],
      paro: "Return left leg to ready position.",
    },
    {
      id: 6,
      readyPosition: "Parallel stance (naranhi sŏgi) pushing high section double arc hand, at A facing D.",
      pathImg: "/paths/cheonjiin-Il.svg",
      steps: [
        "Step left foot 90° toward B forming a left-foot-forward back stance (oenbal dwissŏgi). Execute a left middle section corkscrew trap, in to out (gama do? olgami). Kihap.",
        "Maintain trap and shift left foot, forming a left-foot-forward front stance (oenbal apsŏgi) facing B. Execute a right reverse high section palm-heel strike (sangdan bandae sonbadak jirŭgi).",
        "Maintain stance and execute a right reverse low section palm-heel strike (hadan bandae sonbadak jirŭgi) to the groin.",
        "Shift from a left foot forward front stance to a left-foot-forward back stance (oenbal dwissŏgi). Simultaneously execute a left middle section palm-heel pushing block (jungdan sonbadak mirŏ makki) while bringing right fist up in a face block (ŏlgul makki) to guard the side of your face.",
        "Step forward toward B forming a right-foot-forward front stance (orŭnbal apsŏgi) and execute a right middle section front punch (jungdan ap jumŏk jirŭgi).",
        "Turn clockwise 180° toward C forming a right-foot-forward back stance (orŭnbal dwissŏgi). Execute a right middle section corkscrew trap, in to out (gama do? olgami), taking care that the circle is large enough to trap an opponent's arm.",
        "Maintain trap and shift right foot, forming a right-foot-forward front stance (orŭnbal apsŏgi) facing C. Execute a left reverse high section palm-heel strike (sangdan bandae sonbadak jirŭgi).",
        "Maintain stance and execute a left reverse low section palm-heel strike (hadan bandae sonbadak jirŭgi) to the groin.",
        "Shift from a right foot forward front stance to a right-foot-forward back stance (orŭnbal dwissŏgi). Simultaneously execute a right middle section palm-heel pushing block (jungdan sonbadak mirŏ makki) while bringing left fist up in a face block (ŏlgul makki) to guard the side of your face.",
        "Step forward toward C forming a left-foot-forward front stance (oenbal apsŏgi) and execute a left middle section front punch (jungdan ap jumŏk jirŭgi).",
        "Step left foot 90° toward D to form a left-foot-forward front stance (oenbal apsŏgi) and execute a low section X-forearm block (hadan gyoch'a p'almok makki).",
        "Step forward with the right foot onto line AD and form a horse stance (gima sŏgi). Execute a right outside forearm block (bakkat p'almok makki).",
        "Execute a right leg step-behind side thrust kick (baldwiro olmkyŏ yŏp ch'agi) toward D.",
        "Land in a horse stance (gima sŏgi) and execute a right middle section augmented side elbow strike (jungdan yŏp p'alkkumch'i ddaerigi) toward D. Kihap.",
        "Pivot counter-clockwise with your left foot toward E, forming a left-foot-forward front stance (oenbal apsŏgi) and executing a left middle section augmented forearm block (jungdan gŏdŭrŏ makki).",
        "Maintain stance and execute a right reverse high section spearhand strike (sangdan bandae son'kkŭt jirŭgi) with your palm downward.",
        "Bring left foot to right foot forming a closed stance (moasŏgi) with your body facing A and your head turned toward E. Execute a left high section downward hammerfist strike (sangdan naeryŏ mejumŏk ddaerigi).",
        "Step right 90° toward F, forming a right-foot-forward front stance (orŭnbal apsŏgi) and executing a right middle section augmented forearm block (jungdan gŏdŭrŏ makki).",
        "Maintain stance and execute a left reverse high section spearhand strike (sangdan bandae son'kkŭt jirŭgi) with your palm downward.",
        "Bring right foot to left foot forming a closed stance (moasŏgi) with your body facing A and your head turned toward F. Execute a right high section downward hammerfist strike (sangdan naeryŏ mejumŏk ddaerigi).",
        "Step forward toward A with your right foot, forming a right-foot-forward front stance (orŭnbal apsŏgi) and executing a low section X-forearm block (hadan gyoch'a p'almok makki).",
        "Step forward with the left foot onto line AD and form a horse stance (gima sŏgi). Execute a left outside forearm block (bakkat p'almok makki).",
        "Execute a left leg step-behind side thrust kick (baldwiro olmkyŏ yŏp ch'agi) toward A.",
        "Land in a horse stance (gima sŏgi) and execute a left middle section augmented side elbow strike (jungdan yŏp p'alkkumch'i ddaerigi) toward A.",
        "Step right foot past left foot, pivot 90° so that you are facing D and shift your left foot into a parallel stance (naranhi sŏgi) while executing a major hip throw (o-goshi) over your left hip. Kihap.",
        "Pivot left foot 90° toward B and form a left-foot-forward back stance (oenbal dwissŏgi). Execute a left deflection block (bansa jagyong makki).",
        "Execute a right leg roundhouse kick (dollyŏ ch'agi) toward B.",
        "Land forming a right-foot-forward front stance (orŭnbal apsŏgi). Execute a right middle section forearm block (jungdan p'almok makki).",
        "Maintain stance. Execute a left reverse high section arc-hand strike (sangdan bandae bandalson jirŭgi).",
        "Pivot clockwise 180° toward C and form a right-foot-forward back stance (orŭnbal dwissŏgi). Execute a right deflection block (bansa jagyong makki).",
        "Execute a left leg roundhouse kick (dollyŏ ch'agi) toward C.",
        "Land forming a left-foot-forward front stance (oenbal apsŏgi). Execute a left middle section forearm block (jungdan p'almok makki).",
        "Maintain stance. Execute a right reverse high section arc-hand strike (sangdan bandae bandalson jirŭgi). Kihap."
      ],
      paro: "Return left leg to ready position."
    
    },
    {
      id: 5,
      readyPosition: "Parallel stance (naranhi sŏgi) pushing low double arc hand, at A facing D.",
      pathImg: "/paths/cheonjiin-yee.svg",
      steps: [  
        "Move left foot to form a horse stance (gima sŏgi) on line AB, facing forward. Execute a right high section augmented rolling vertical punch (sangdan sewŏ jumŏk jirŭgi) with the left hand under the right elbow. Kihap.",
        "Shift left foot 90° toward B forming a left-foot-forward back stance (oenbal dwissŏgi) and execute a left middle section outward ridgehand block (jungdan bakkŭro yŏksonk'al makki).",
        "Step forward toward B forming a right-foot-forward front stance (orŭnbal apsŏgi) and execute a low section palm-heel strike (hadan sonbadak jirŭgi) to the groin.",
        "Pivot 180° back toward A forming a right-foot-forward back stance (orŭnbal dwissŏgi), and execute a right middle section outward ridgehand block (jungdan bakkŭro yŏksonk'al makki).",
        "Step forward toward C forming a left-foot-forward front stance (oenbal apsŏgi) and execute a low section palm-heel strike (hadan sonbadak jirŭgi) to the groin.",
        "Step 90° toward D with the left foot, forming a left-foot-forward front stance (oenbal apsŏgi), and execute a low section knifehand block (hadan sonk'al makki).",
        "Maintain stance. Pull left hand to right side in a stacking chamber with left hand on top. Simultaneously execute a left high section knifehand block (sangdan sonk'al makki) and a right reverse high section inward knifehand strike (sangdan bandae anŭro sonk'al ddaerigi).",
        "Move forward toward D executing a right leg front snap kick (ap ch'agi).",
        "Land in a right-foot-forward front stance (orŭnbal apsŏgi), executing a right middle section augmented vertical spearhand strike (jungdan sewŏ son'kkŭt jirŭgi).",
        "Maintain stance. Execute a right wrist-grab escape (sonmok japki p'ulgi).",
        "Maintain stance. Execute a right high section downward backfist strike (sangdan naeryŏ dŭngjumŏk ddaerigi) with your knuckles facing forward.",
        "Move forward executing a left leg roundhouse kick (dollyŏ ch'agi).",
        "Land in a transitional stance. Move forward executing a right leg roundhouse kick (dollyŏ ch'agi).",
        "Land forming a right-foot-forward back stance (orŭnbal dwissŏgi), executing a middle section double knifehand block (jungdan dul sonk'al makki).",
        "Move left leg 270° counter-clockwise, forming a left-foot-forward back stance (oenbal dwissŏgi) facing E. Stack and execute a knifehand box block (ssang son sonk'al makki).",
        "Step forward into a right-foot-forward front stance (orŭnbal apsŏgi), executing a right middle section vertical punch (jungdan sewŏ jumŏk jirŭgi). At the same time, execute a left hand reverse palm-heel face block (bandae sonbadak ŏlgul makki), bringing your left hand to the right side of your face.",
        "Turn 180° clockwise, forming a right-foot-forward back stance (orŭnbal dwissŏgi) facing F. Stack and execute a knifehand box block (ssang son sonk'al makki).",
        "Step forward into a left-foot-forward front stance (oenbal apsŏgi), executing a left middle section vertical punch (jungdan sewŏ jumŏk jirŭgi). At the same time, execute a right hand reverse palm-heel face block (bandae sonbadak ŏlgul makki), bringing your right hand to the left side of your face.",
        "Step 90° toward A with the left foot, forming a left-foot-forward front stance (oenbal apsŏgi) and execute a low section knifehand block (hadan sonk'al makki).",
        "Maintain stance. Pull left hand to right side in a stacking chamber with left hand on top. Simultaneously execute a left high section knifehand block (sangdan sonk'al makki) and a right reverse high section inward knifehand strike (sangdan bandae anŭro sonk'al ddaerigi).",
        "Move forward, executing a right leg roundhouse kick (dollyŏ ch'agi).",
        "Land in a right-foot-forward back stance (orŭnbal dwissŏgi) facing A. Execute a middle section Kyuki-Do block (jungdan gyŏkkido makki).",
        "Grab opponent's right arm and left lapel and move your left foot past your right foot, pivot 90° and shift your right foot into a parallel stance (naranhi sŏgi) facing D. Execute a two-handed shoulder throw (morote seoi-nage).",
        "Step forward toward D into a left-foot-forward front stance (oenbal apsŏgi) and execute a reverse downward palm-heel strike (bandae naeryŏ sonbadak jirŭgi). Kihap.",
        "From your current stance, look 180° over your left shoulder and execute a left leg side thrust kick (yŏp ch'agi) toward A.",
        "Land forming a left-foot-forward back stance (oenbal dwissŏgi) facing A. Execute a middle section Kyuki-Do block (jungdan gyŏkkido makki).",
        "Grab opponent's right arm and step forward, bringing your right arm up under their right arm. Move your left foot past your right foot, pivot 90° and shift your right foot into a parallel stance (naranhi sŏgi) facing D. Execute a one-armed shoulder throw (ippon seoi-nage).",
        "Straighten up and execute a right foot stomping kick (balba ch'agi). Return right foot to a closed stance (moasŏgi). Kihap.",
        "Look 180° over left shoulder and execute a left leg side thrust kick (yŏp ch'agi) toward A.",
        "Land forming a left-foot-forward back stance (oenbal dwissŏgi) facing A. Execute a middle section Kyuki-Do block (jungdan gyŏkkido makki).",
        "Pivot 180° on left foot and execute a right rear leg side thrust kick (dwitpal yŏp ch'agi) toward A.",
        "Land forming a left-foot-forward cat stance (oenbal goyangi sŏgi) at A facing D. Execute a right reverse middle section vertical punch (jungdan bandae sewŏ jumŏk jirŭgi). At the same time, execute a left hand palm-heel face block (sonbadak ŏlgul makki), bringing your left hand to the right side of your face.",
        "Step forward with your left foot into a left-foot-forward front stance (oenbal apsŏgi) executing a right hand reverse high section spearhand strike (sangdan bandae son'kkŭt jirŭgi). Kihap."
      ],
      paro: "Return right leg to ready position."
    },
    {
      id: 4,
      readyPosition: "Parallel stance (naranhi sŏgi) pushing middle section double arc hand, at A facing forward.",
      pathImg: "/paths/cheonjiin-sam.svg",
      steps: [  
        "Step left foot toward B, forming a left classical Kyuki-Do stance (oenbal gyŏkkido sŏgi) with your feet along line AB. Look back over your right shoulder toward A and execute a modified Kyuki-Do block (byŏn'gyŏng gyŏkido makki). Kihap.",
        "Jump forward, bringing left foot toward right foot. Execute a right leg connecting side thrust kick (iŏ yŏp ch'agi) away from B.",
        "Land in a left-foot-forward back stance (oenbal dwissŏgi) facing B. Execute a middle section double knifehand block (jungdan dul sonk'al makki).",
        "Note: the following three movements are executed in quick succession. Step forward toward B into a transitional stance, executing a right hand high section inward knifehand strike (sangdan anŭro sonk'al ddaerigi).",
        "Pivot on right foot, bringing left foot around 180° into a transitional stance facing B while executing a high section outward knifehand strike (sangdan bakkŭro sonk'al ddaerigi).",
        "Step forward into a right-foot-forward front stance (orŭnbal apsŏgi) facing B while executing a right hand high section inward knifehand strike (sangdan anŭro sonk'al ddaerigi).",
        "Execute a connecting front snap kick (iŏ ap ch'agi) toward B.",
        "Land in a right-foot-forward front stance (orŭnbal apsŏgi) and execute a high section normal cross choke (nami jūji-jime) with right hand over left. Bend left knee and shift backwards while bringing your hands to your chest to complete the choke.",
        "Straighten your left knee and shift forward in a right-foot-forward front stance (orŭnbal apsŏgi) again. Execute a right hand high section knifehand block (sangdan sonk'al makki), catching opponent under the chin and snapping their head up and back.",
        "Maintain stance and execute a left hand reverse high section arc-hand strike (sangdan bandae bandalson jirŭgi).",
        "Pivot on right foot and execute a left roundhouse kick (dollyŏ ch'agi) toward B.",
        "Land in a transitional stance and execute a 180° spinning hook kick (dwidollyŏ gŏlch'yŏ ch'agi) toward B.",
        "Land in a left-foot-forward back stance (oenbal dwissŏgi) at B facing A. Execute a guarding block (daebi makki).",
        "Jump forward and land in an X-stance (gyoch'a sŏgi) with your left foot behind your right foot while executing a high section vertical backfist strike (sangdan sewŏ dŭngjumŏk ddaerigi).",
        "Pivot counter-clockwise 180°, unwinding into a left-foot-forward back stance (oenbal dwissŏgi) with a high section outward knifehand strike (sangdan bakkŭro sonk'al ddaerigi).",
        "Step forward toward A forming a right-foot-forward front stance (orŭnbal apsŏgi). Execute a middle section front punch (jungdan ap jumŏk jirŭgi).",
        "Step forward toward A forming a left-foot-forward front stance (oenbal apsŏgi), executing a middle section twin palm-heel strike (jungdan ssang sonbadak jirŭgi). Kihap.",
        "Move left foot, forming a transitional parallel stance (naranhi sŏgi) along line AB. Execute a clockwise jump. Land in a right-foot-forward back stance (orŭnbal dwissŏgi) facing C. Execute a middle section double knifehand block (jungdan dul sonk'al makki).",
        "Note: the following three movements are executed in quick succession. Step forward toward C into a transitional stance, executing a left hand high section inward knifehand strike (sangdan anŭro sonk'al ddaerigi).",
        "Pivot on left foot, bringing right foot around 180° into a transitional stance facing C while executing a high section outward knifehand strike (sangdan bakkŭro sonk'al ddaerigi).",
        "Step forward into a left-foot-forward front stance (oenbal apsŏgi) facing C while executing a left hand high section inward knifehand strike (sangdan anŭro sonk'al ddaerigi).",
        "Execute a connecting front snap kick (iŏ ap ch'agi) toward C.",
        "Land in a left-foot-forward front stance (oenbal apsŏgi) and execute a high section normal cross choke (nami jūji-jime) with left hand over right. Bend right knee and shift backwards while bringing your hands to your chest to complete the choke.",
        "Straighten your right knee and shift forward in a left-foot-forward front stance (oenbal apsŏgi) again. Execute a left hand high section knifehand block (sangdan sonk'al makki), catching opponent under the chin and snapping their head up and back.",
        "Maintain stance and execute a right hand reverse high section arc-hand strike (sangdan bandae bandalson jirŭgi).",
        "Pivot on left foot and execute a right roundhouse kick (dollyŏ ch'agi) toward C.",
        "Land in a transitional stance and execute a 180° spinning hook kick (dwidollyŏ gŏlch'yŏ ch'agi) toward C.",
        "Land in a right-foot-forward back stance (orŭnbal dwissŏgi) at C facing A. Execute a guarding block (daebi makki).",
        "Jump forward and land in an X-stance (gyoch'a sŏgi) with your right foot behind your left foot while executing a high section vertical backfist strike (sangdan sewŏ dŭngjumŏk ddaerigi).",
        "Pivot clockwise 180°, unwinding into a right-foot-forward back stance (orŭnbal dwissŏgi) with a high section outward knifehand strike (sangdan bakkŭro sonk'al ddaerigi).",
        "Step forward toward A forming a left-foot-forward front stance (oenbal apsŏgi). Execute a middle section front punch (jungdan ap jumŏk jirŭgi).",
        "Step backward with your left leg, forming a right-foot-forward kneeling front stance (orŭnbal murŭp kkulhŏ sŏgi). Execute a right hand middle section knifehand block (jungdan sonk'al makki).",
        "Execute a right forward roll (zenpo kaiten) toward A. Land at A in a right-foot-forward kneeling front stance (orŭnbal murŭp kkulhŏ sŏgi). As you come out of the roll, execute a right high section knifehand block (sangdan sonk'al makki) and a left reverse upward ridgehand strike (bandae wi yŏk sonk'al ddaerigi) to opponent's groin. Kihap."
      ],
      paro: "Return left foot to ready position."
    },
    {
      id: 3,
      readyPosition: "Closed ready stance, staff to right side, at A facing forward.",
      pathImg: "/paths/mannam.svg",
      steps: [ 
        "Step out with your left foot into a parallel stance (naranhi sŏgi) at A, facing the front of the room. Execute a slow pushing twin high section horizontal block (). There is no kihap on this move.",
        "Maintain stance and execute a twin low section horizontal block ().",
        "Turn left toward B forming a left-foot-forward front stance (oenbal apsŏgi). As you are doing this, reverse your grip with your left hand and execute a downward strike (). Kihap.",
        "Shift your weight back and form a left-foot-forward back stance (oenbal dwissŏgi) on line AB facing B. Execute a classical box block ().",
        "Bring your right foot forward into a transitional closed stance and let the staff drop to your right side. Step toward B with your left foot, forming a left-foot-forward front stance (oenbal apsŏgi). Execute a reverse middle section poke ().",
        "Note: the next three movements are done rapidly and illustrate Body Conditioning (). Maintain stance. Execute a low section strike ().",
        "Maintain stance. Execute a middle section strike ().",
        "Maintain stance. Execute a high section strike ().",
        "Pivot on left foot clockwise toward A and land in a right-foot-forward front stance (orŭnbal apsŏgi) along line AB facing A. Execute a reverse middle section poke ().",
        "Note: the next eight movements illustrate Theory () and Body Conditioning (). Step forward toward E into a left-foot-forward front stance (oenbal apsŏgi). Execute a reverse middle section poke ().",
        "Maintain stance and execute a downward strike () toward the clavicle.",
        "Maintain stance and execute a reverse middle section poke ().",
        "Maintain stance and execute an upward strike () towards the groin.",
        "Maintain stance and execute a reverse middle section poke ().",
        "Maintain stance and execute a high section strike () (right to left), allowing the end of the staff to strike the outside of your arm.",
        "Maintain stance and execute a high section strike () (left to right), allowing the end of the staff to strike the outside of your arm.",
        "Maintain stance and execute a high section strike () (right to left), allowing the end of the staff to strike the outside of your arm.",
        "Pivot on left leg toward C, forming a right-foot-forward front stance (orŭnbal apsŏgi). As you are doing this, reverse your grip with your left hand and execute a downward strike (). Kihap.",
        "Shift your weight back and form a right-foot-forward back stance (orŭnbal dwissŏgi) on line AC facing C. Execute a classical box block ().",
        "Bring your left foot forward into a transitional closed stance (moasŏgi) and let the staff drop to your left side. Step toward C with your right foot, forming a right-foot-forward front stance (orŭnbal apsŏgi). Execute a reverse middle section poke ().",
        "Note: the next three movements are done rapidly and illustrate Body Conditioning (). Maintain stance. Execute a low section strike ().",
        "Maintain stance. Execute a middle section strike ().",
        "Maintain stance. Execute a high section strike ().",
        "Pivot on right foot counter-clockwise toward A and land in a left-foot-forward front stance (oenbal apsŏgi) along line AC facing A. Execute a reverse middle section poke ().",
        "Reverse grip with right hand and step forward toward D, forming a right-foot-forward transitional stance (). Start executing a right hand figure eight (). This is the first twirl.",
        "Maintain stance. Continue executing right hand figure eight (). This is the second twirl.",
        "Maintain stance. Continue executing right hand figure eight (). This is the third twirl.",
        "Step forward toward D, forming a left-foot-forward transitional stance (). Switch grip to left hand and begin executing a left hand figure eight (). This is the first twirl.",
        "Maintain stance. Continue executing left hand figure eight (). This is the second twirl.",
        "Maintain stance. Continue executing left hand figure eight (). This is the third twirl.",
        "Step forward into a right-foot-forward front stance (orŭnbal apsŏgi) while catching the staff on your right side. Execute a right middle section poke ().",
        "Step forward toward D into a left-foot-forward front stance (oenbal apsŏgi). Let go with your left hand and shift your left grip to the bottom of the staff. Execute an overhead strike () down and to the left at a 45° angle. Kihap.",
        "Draw right leg up into a one-legged stance (han bal sŏgi). Execute a high-low classical pose () with the bottom hand open.",
        "Note: the next three moves are done together and illustrate Manipulation (). Put your right foot down so that you are on line DE facing the front of the room. Slide your right hand to the center of the staff, palm inward. Turn your right hand clockwise, so that the palm faces away from you, causing the staff to spin 180°.",
        "Step clockwise with your left foot landing in a transitional horse stance (gima sŏgi) along line DE facing the back of the room. As you step, bring the staff behind your back and switch from a right grip to a left grip.",
        "Bring the staff back in front of you with your left hand facing palm out. Put the back of your right hand against the staff, with your palm facing you. Use your left hand to spin the staff clockwise into your right hand. As you are doing this, step clockwise with your right foot, ending up in a right-foot-forward back stance (orŭnbal dwissŏgi) along line DE, facing E. While you are stepping, continue spinning the staff clockwise with your right hand. At the end of the spin, allow the end of the staff to strike you in the back while you execute a left hand reverse high section knifehand block (sangdan bandae sonk'al makki).",
        "Step forward with your left foot into a left-foot-forward front stance (oenbal apsŏgi). Pass the staff over your right shoulder, from your right hand to your left hand.",
        "Maintain stance. Execute a reverse middle section poke ().",
        "Maintain stance. Execute a low section foot sweep (), using your right hand to drive the staff.",
        "Maintain stance. Execute a reverse high section strike (), ending with the staff tucked under your right arm.",
        "Bring your right foot to your left foot, executing a left leg connecting front snap kick (iŏ ap ch'agi). As you land, step toward E with your right foot, forming a transitional stance along line DE.",
        "Step toward E with your left foot, ending up in an X-stance (gyoch'a sŏgi) with your left foot behind your right. Execute a side poke () toward your right side, ending with the staff tucked under the left arm. Kihap.",
        "Draw left leg up into a one-legged stance (han bal sŏgi). Execute a high-low classical pose () with the bottom hand open.",
        "Put left foot down along line EA, facing A in a left-foot-forward front stance (oenbal apsŏgi). Execute a high section double horizontal block ().",
        "Step forward with your right foot into a right-foot-forward front stance (orŭnbal apsŏgi) and execute a low section block (), ending with your left hand tucked under your right arm, and your right arm fully extended.",
        "Step forward toward A, executing a counter-clockwise overhead spin ().",
        "Land in a left-foot-forward front stance (oenbal apsŏgi) and execute a low section block (), ending with your right hand tucked under your left arm, and your left arm fully extended.",
        "Bring your right foot up to your left foot in a transitional closed stance (moasŏgi). Step out with your left foot and kneel down in a left-foot-forward kneeling front stance (oenbal murŭp kkulhŏ sŏgi). Execute a reverse high section poke ().",
        "Maintain stance while executing a low section foot sweep ().",
        "Execute a downward strike () from left to right, with your left hand as the driver. Kihap.",
        "Paro: Step up with your left foot into a parallel stance (naranhi sŏgi) at A, facing the front of the room. Execute a slow pushing twin high section horizontal block ().",
        "Maintain stance and execute a twin low section horizontal block ()."
      ],
      paro: "Return left leg to ready position."
    },
    {
      id: 2,
      readyPosition: "Parallel stance (naranhi sŏgi) with hip-high twin vertical spearhand push, at A facing forward.",
      pathImg: "/paths/kachi.svg",
      steps: [
        "Reach up with both hands and execute a sleeve and lapel grab. Pull downward and to your right, executing a propping ankle throw (sasae tsurikomi ashi) with your right foot. Kihap. Set your right foot down to form a transitional stance toward B.",
        "Pivot on right foot toward B and execute a left low section roundhouse kick (hadan dollyŏ ch'agi).",
        "Land in a left-foot-forward front stance (oenbal apsŏgi) facing B. Execute a right reverse high section ridgehand strike (sangdan bandae yŏksonk'al ddaerigi).",
        "Move toward B with a right rear leg hook kick (dwitpal gŏlch'yŏ ch'agi), landing in a transitional stance.",
        "Execute a left low section rear leg side thrust kick (hadan dwitpal yŏp ch'agi). Land in a left-foot-forward front stance (oenbal apsŏgi) facing B.",
        "Execute a sleeve and lapel grab followed by a knee strike (murŭp ch'agi) with the right knee.",
        "Maintain stance and grip. Execute a second knee strike (murŭp ch'agi) with the right knee.",
        "Step right foot behind left (facing A) and extend left leg while executing a body drop throw (tai otoshi) over the left leg.",
        "Follow through with the throw by placing left knee on the ground and executing a right leg foot-sweep/drop spinning hook kick (murŭp kkulhŏ dwidollyŏ gŏlch'yŏ ch'agi) across line AB to your rear.",
        "Keeping your weight on your left knee, pivot back so you are facing A. Execute a right leg low section kneeling roundhouse kick (hadan murŭp kkulhŏ dollyŏ ch'agi) to the front/right of the room.",
        "Set your right leg down, forming a right-foot-forward kneeling front stance (orŭnbal murŭp kkulhŏ sŏgi) facing A. Execute a right hand palm-heel face block (sonbadak ŏlgul makki) with your right hand pushing to the left.",
        "As you stand up into a right-foot-forward front stance (orŭnbal apsŏgi) execute a left hand reverse middle section knifehand block (jungdan bandae sonk'al makki).",
        "As you finish standing, execute a right hand high section palm-heel strike (sangdan sonbadak jirŭgi).",
        "Maintain stance. Execute a right hand middle section knifehand block (jungdan sonk'al makki).",
        "Maintain stance. Execute a left hand reverse high section palm-heel strike (sangdan bandae sonbadak jirŭgi).",
        "Maintain stance. Execute a right high section front elbow strike (sangdan ap p'alkkumch'i ddaerigi). Do not strike left hand with right elbow.",
        "Reach up with both hands and execute a sleeve and lapel grab. Pull downward and to your left, executing a sliding ankle throw (okuri-ashi harai) with your left foot. Kihap. Set your left foot down to form a transitional stance toward C.",
        "Pivot on left foot toward C and execute a right low section roundhouse kick (hadan dollyŏ ch'agi).",
        "Land in a right-foot-forward front stance (orŭnbal apsŏgi) facing C. Execute a left reverse high section ridgehand strike (sangdan bandae yŏksonk'al ddaerigi).",
        "Move toward C with a left rear leg hook kick (dwitpal gŏlch'yŏ ch'agi), landing in a transitional stance.",
        "Execute a right low section rear leg side thrust kick (hadan dwitpal yŏp ch'agi). Land in a right-foot-forward front stance (orŭnbal apsŏgi) facing C.",
        "Execute a high section sleeve and lapel grab followed by a knee strike (murŭp ch'agi) with the left knee.",
        "Maintain stance and grip. Execute a second knee strike (murŭp ch'agi) with the left knee.",
        "Step left foot behind right (facing A) and extend right leg while executing a body drop throw (tai otoshi) over the right leg.",
        "Follow through with the throw by placing right knee on the ground and executing a left leg drop spinning hook kick (murŭp kkulhŏ dwidollyŏ gŏlch'yŏ ch'agi) across line AC to your rear.",
        "Keeping your weight on your right knee, pivot back so you are facing A. Execute a left leg low section kneeling roundhouse kick (hadan murŭp kkulhŏ dollyŏ ch'agi) to the front/right of the room.",
        "Set your left leg down, forming a left-foot-forward kneeling front stance (oenbal murŭp kkulhŏ sŏgi) facing A. Execute a left hand palm-heel face block (sonbadak ŏlgul makki) with your left hand pushing to the right.",
        "As you stand up into a left-foot-forward front stance (oenbal apsŏgi) execute a right hand reverse middle section knifehand block (jungdan bandae sonk'al makki).",
        "As you finish standing, execute a left hand high section palm-heel strike (sangdan sonbadak jirŭgi).",
        "Maintain stance. Execute a left hand middle section knifehand block (jungdan sonk'al makki).",
        "Maintain stance. Execute a right hand reverse high section palm-heel strike (sangdan bandae sonbadak jirŭgi).",
        "Maintain stance. Execute a left high section front elbow strike (sangdan ap p'alkkumch'i ddaerigi). Strike your right hand with your left elbow.",
        "Step forward with your right foot, forming a horse stance (gima sŏgi) along line AC facing the front of the room. Execute an X-grab trap (gyoch'a olgami) by bringing your left hand out in a hooking block and your right hand across in a grab. This should end up looking similar to a knifehand X-block (sonk'al gyoch'a makki).",
        "Maintain stance. Execute an arm pull (dan-gigi) by pulling both hands downward to your right hip in a stacked position with the left hand open. This is an arm wrench (cho-igi).",
        "Maintain stance. Execute a left high section knifehand block (sangdan sonk'al makki). Simultaneously execute a right high section uppercut (sangdan dwijibŏ jirŭgi) to your opponent's chin.",
        "Pull both hands back to your sides and execute a high section twin thumb strike (sangdan ssang ŏmjison'garak jirŭgi). Kihap."
      ],
      paro: "Return left leg to ready position."
    },
    {
      id: 1,
      readyPosition: "Parallel stance (naranhi sŏgi) pushing high section double arc hand, at A facing D.",
      pathImg: "/paths/sarang.svg",
      steps: [
        "Left foot moves toward B to form a left-foot-forward back stance (oenbal dwissŏgi). Execute middle section inside forearm block (jungdan an p'almok makki). Kihap.",
        "Maintain stance. Execute a right reverse middle section turning punch (jungdan bandae dollyŏ ap jumŏk jirŭgi).",
        "Step forward toward B, forming a right-foot-forward front stance (orŭnbal apsŏgi). Execute a slow middle section knifehand block (jungdan sonk'al makki).",
        "Maintain stance. Execute a left reverse middle section front punch (jungdan bandae ap jumŏk jirŭgi).",
        "Execute a low section rear leg side thrust kick (hadan dwitpal yŏp ch'agi) toward B. Set foot down into a transitional stance.",
        "Turn clockwise and execute a tornado kick (t'oneido ch'agi) toward B. Right leg is the driver and left leg kicks.",
        "Land in a left-foot-forward back stance (oenbal dwissŏgi) facing B. Execute a left hand high section downward backfist strike (sangdan naeryŏ dŭngjumŏk ddaerigi) toward B. This technique should strike downward rather than across.",
        "Shift your feet into a horse stance (gima sŏgi) along line AB and execute a right high section outward knifehand strike (sangdan bakkŭro sonk'al ddaerigi) toward A.",
        "Turn your right hand so the thumb is up. Execute a left outside-to-inside crescent kick (ap dollyŏ ch'agi), striking your right palm with the inside edge of your foot. Set down in a horse stance (gima sŏgi) along line AB, with your left foot closest to A.",
        "Maintain stance and execute a left high section front elbow strike (sangdan ap p'alkkumch'i ddaerigi), striking your right palm with your elbow.",
        "Maintain stance and execute a left middle section knifehand block (jungdan sonk'al makki).",
        "Step right leg 180° counter-clockwise toward A, forming a horse stance (gima sŏgi) along line AB. Execute a right middle section side punch (jungdan yŏp jumŏk jirŭgi).",
        "Return left foot to ready position (junbi sŏgi), but this time the right hand is over the left.",
        "Right foot moves toward C to form a right-foot-forward back stance (orŭnbal dwissŏgi). Execute middle section inside forearm block (jungdan an p'almok makki). Kihap.",
        "Maintain stance. Execute a left reverse middle section turning punch (jungdan bandae dollyŏ ap jumŏk jirŭgi).",
        "Step forward toward C, forming a left-foot-forward front stance (oenbal apsŏgi). Execute a slow middle section knifehand block (jungdan sonk'al makki).",
        "Maintain stance. Execute a right reverse middle section front punch (jungdan bandae ap jumŏk jirŭgi).",
        "Execute a low section rear leg side thrust kick (hadan dwitpal yŏp ch'agi) toward C. Set right foot down into a transitional stance.",
        "Turn clockwise and execute a tornado kick (t'oneido ch'agi) toward C. Left leg is the driver and right leg kicks.",
        "Land in a right-foot-forward back stance (orŭnbal dwissŏgi) facing C. Execute a right hand high section downward backfist strike (sangdan naeryŏ dŭngjumŏk ddaerigi) toward C. This technique should strike downward rather than across.",
        "Shift your feet into a horse stance (gima sŏgi) along line AC and execute a left high section outward knifehand strike (sangdan bakkŭro sonk'al ddaerigi) toward A.",
        "Turn your left hand so the thumb is up. Execute a right outside-to-inside crescent kick (ap dollyŏ ch'agi), striking your left palm with the inside edge of your foot. Set down in a horse stance (gima sŏgi) along line AC, with your right foot closest to A.",
        "Maintain stance and execute a right high section front elbow strike (sangdan ap p'alkkumch'i ddaerigi), striking your left palm with your elbow.",
        "Maintain stance and execute a right middle section knifehand block (jungdan sonk'al makki).",
        "Step left leg 180° counter-clockwise toward A, forming a horse stance (gima sŏgi) along line AC. Execute a left middle section side punch (jungdan yŏp jumŏk jirŭgi).",
        "Shift right foot toward left foot and left foot toward D, forming a deep left-foot-forward front stance (oenbal apsŏgi). Stack your hands at your right hip and execute a middle section twin palm-heel pushing block (jungdan ssang sonbadak mirŏ makki) (a 'push the rock' block).",
        "Execute a right leg front snap kick (ap ch'agi) toward D.",
        "Land in a right-foot-forward front stance (orŭnbal apsŏgi), executing a high section inward twin knifehand strike (sangdan anŭro ssang sonk'al ddaerigi).",
        "Move right foot over to the left and pivot on right foot 180° counter-clockwise toward E, forming a left-foot-forward front stance (oenbal apsŏgi) facing E. Execute a right reverse high section four-knuckle strike (sangdan bandae p'yŏnjumŏk jirŭgi), with your left hand ending up under your right elbow.",
        "Shift left foot toward right foot and right foot toward E, forming a deep right-foot-forward front stance (orŭnbal apsŏgi). Stack your hands at your left hip and execute a middle section twin palm-heel pushing block (jungdan ssang sonbadak mirŏ makki) (a 'push the rock' block).",
        "Execute a left leg front snap kick (ap ch'agi) toward E.",
        "Land in a left-foot-forward front stance (oenbal apsŏgi), executing a high section inward twin knifehand strike (sangdan anŭro ssang sonk'al ddaerigi).",
        "Move left foot over to the right and pivot on left foot 180° toward D, forming a right-foot-forward front stance (orŭnbal apsŏgi) facing D. Execute a left reverse high section four-knuckle strike (sangdan bandae p'yŏnjumŏk jirŭgi), with your right hand ending up under your left elbow. Kihap."
      ],
      paro: "Return left leg to ready position."
    }
  ];
  